development:
  adapter:  postgresql
  encoding: unicode
  database: graphql_rails_development
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: graphql_rails_test
  pool:     5

